api version: v1
kind: pod
metadata:
   name: sample1
   labels:
     app: nginx
spec:
    containers:
      - name: nginx
        image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: sample1
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: TCP
      targetPort: 80
      port: 80
  type: LoadBalancer